export type HeroSectionLayout =
    | 'Default hero section' // supported
    | 'Visual image with heading'
    | 'Search bar with datepicker'
    | 'Email sign-up with video'
    | 'Illustration with email sign-up'
    | 'Cover image with CTAs'
    | 'Informational CTA with app screenshot'
    | 'Hero section with search bar'
    | 'Video embed with CTA'
    | 'Sign-up form with CTA'
    | 'App screenshot with CTAs'
    | 'Background cover image with CTAs'
    | 'Financial exchange (crypto)'
    | 'Hero section with carousel slider'
    | 'Hero section with book cover'
    | 'Blog posts with featured image'
    | 'Phone mockup with app download'

export type HeroSectionBlockType =
    | 'background-image'
    | 'overlay'
    | 'title'
    | 'sub-title'
    | 'under'
